### ISSUE TITLE
Installation step missing?

### ISSUE THREAD

**Issue by hvwaldow** [mfraezz/DirectoryOfRepositories#5]
Following the installation procedure I can successfully run the test server and also "navigate to http://localhost:8000/swag/ to view a list of API endpoints". I can not do much else, because I get errors about missing database tables. E.g.

> OperationalError at /submit/Repositories/
> no such table: dor_contenttype

 It seems that all tables named `dor_*` were not created. What am I missing here?

**Comment by mfraezz** [comment]
I've hardly touched this in years, but it looks like this is because the `clean_build` script deletes everything `dor/migrations` and `makemigrations` doesn't create new things because it doesn't see an `__init__`. I'll have a small fix for this up to `develop` shortly.

What's your use case for this repo, @hvwaldow, if you don't mind my asking?

**Comment by hvwaldow** [comment]
Thanks, @mfraezz. Works like a charm after your fix!

> What's your use case for this repo, @hvwaldow, if you don't mind my asking?

 I stumbled across https://copdessdirectory.osf.io/, which looks quite useful, and I might be interested to use this repo to set up a crowd-sourced / curated list of data portals for freshwater science. This is not particularly urgent. It is clear this this repo is not very active, so wanted to assess the necessary effort on my side to a) get that running and b) customize it. And now I am all set for b).
